### Invoke Poject 1 users Method
GET http://localhost:3001/users

### Invoke Poject 1 Add Method
GET http://localhost:3001/add

### Invoke Poject 1 Power Method
GET http://localhost:3001/power



### Invoke Poject 2 health Method
GET http://localhost:3002/health
